import json, base64, os
D = {
"teller": {"title":"Teller Approach Animation","label":"Teller","wh":[1312,400],"layers":4,
 "stages":[
  {"sub":"Process, sized to constraints","copy":"The programme was planned as one big-bang release covering every withdrawal, payment and deposit transaction type, but we designed them one at a time.","note":"Circles fade in left to right, each followed by its arrow. Stage names fade in with them; the last is Release."},
  {"sub":"Process, sized to constraints","copy":"The programme was planned as one big-bang release covering every withdrawal, payment and deposit transaction type, but we designed them one at a time. Each ran its own design process, sized to its breadth and complexity, and to the time and capacity we actually had.","note":"Withdrawal floor appears, then its dot columns grow upward from the floor, left to right (one column per transaction type, height = rigour of process)."},
  {"sub":"Process, sized to constraints","copy":"The programme was planned as one big-bang release covering every withdrawal, payment and deposit transaction type, but we designed them one at a time. Each ran its own design process, sized to its breadth and complexity, and to the time and capacity we actually had.","note":"Two annotations appear: \"One column: one transaction type\" (pointer to a column) and \"Height: Rigour of process\" (height marker)."},
  {"sub":"Process, sized to constraints","copy":"The programme was planned as one big-bang release covering every withdrawal, payment and deposit transaction type, but we designed them one at a time. Each ran its own design process, sized to its breadth and complexity, and to the time and capacity we actually had.\n\nSome got deep discovery: time in branch, moderated testing and workshops with our SMEs. Others didn't have that luxury, so the process flexed to match.","note":"Deposit, then Payment floors and dot columns grow in sequentially, left to right."}]},
"budgets": {"title":"Budgets Approach Animation","label":"Budgets","wh":[1312,460],"layers":4,
 "stages":[
  {"sub":"","copy":"The problem was already framed when I joined; how to solve it wasn't.","note":"Problem-space circle and its single dot fade in, labelled \"01 Problem, framed\"."},
  {"sub":"","copy":"The problem was already framed when I joined; how to solve it wasn't.\n\nI ran two rounds of research and testing to define and refine the approach to the budgets feature","note":"Arrow draws to Round 1: a field of open option dots fades in (labels Define, Refine). Arrow to Round 2: the options narrow and a settled slice with its settled dots fills in."},
  {"sub":"","copy":"The problem was already framed when I joined; how to solve it wasn't.\n\nI ran two rounds of research and testing to define and refine the approach to the budgets feature and worked close with my BA and the accessibility team to produce the final detailed figma artefacts","note":"Arrow draws to the detailed stage. Design dot appears, then BA and Accessibility dots; the one-way line from BA draws, then the Design and Accessibility loop."},
  {"sub":"","copy":"The problem was already framed when I joined; how to solve it wasn't.\n\nI ran two rounds of research and testing to define and refine the approach to the budgets feature and worked close with my BA and the accessibility team to produce the final detailed figma artefacts to hand over to engineering.","note":"Arrow draws to the handoff: halo fades in around the black focus dot, labelled \"04 Handoff\"."}]},
"tal": {"title":"TAL Approach Animation","label":"TAL","wh":[1312,460],"layers":3,
 "stages":[
  {"sub":"Learn fast, ship in phases","copy":"I'd never worked in insurance, so I started with immersion: whiteboarding the product landscape with my design lead, a gap analysis of TAL and Suncorp, and pulling apart both quote funnels.","note":"Landscape circle fades in with its open (unknown) dots, then the known dots fill in. Label: 01 Immersion."},
  {"sub":"Learn fast, ship in phases","copy":"I'd never worked in insurance, so I started with immersion: whiteboarding the product landscape with my design lead, a gap analysis of TAL and Suncorp, and pulling apart both quote funnels.","note":"Arrow draws. TAL and Suncorp funnel lines draw left to right with a step dot at each stage, then the five compared spokes drop between them. Label: 02 Gap analysis."},
  {"sub":"Learn fast, ship in phases","copy":"I'd never worked in insurance, so I started with immersion: whiteboarding the product landscape with my design lead, a gap analysis of TAL and Suncorp, and pulling apart both quote funnels. From there I split the journey into five phases — Eligibility, Quick Quote, Underwriting, Review Application, Confirm & Pay — so the team could ship in sprints. Weekly showcases kept stakeholders new to agile in step, and I worked alongside the devs throughout: whiteboarding the architecture, co-designing the progress tracker and QA'ing every build in staging.","note":"Arrow draws. Five phase hubs appear left to right, each joined by a short arrow; Eligibility is the focus. Weekly showcase dots then tick in along the bottom, left to right."}]},
"bx": {"title":"Buildxact Approach Animation","label":"Buildxact","wh":[1312,460],"layers":3,
 "stages":[
  {"sub":"Look at the landscape, not the chair","copy":"I started with evidence rather than opinions: a top-task workshop built on page visits and feature clicks, and an audit of pages, navigation and calls to action.","note":"Evidence pile fades in inside the circle, labelled Top tasks · audit. Label: 01 Evidence."},
  {"sub":"Look at the landscape, not the chair","copy":"I started with evidence rather than opinions: a top-task workshop built on page visits and feature clicks, and an audit of pages, navigation and calls to action. Jesse James Garrett's five planes took us from strategy to structure to skeleton, and four principles tested every idea: Simplified, Personalised, Supported and Connected.","note":"Arrow draws. Four planes stack from the bottom up: Strategy, Scope, Structure, Skeleton, each with its leader line and label. Label: 02 Planes."},
  {"sub":"Look at the landscape, not the chair","copy":"I started with evidence rather than opinions: a top-task workshop built on page visits and feature clicks, and an audit of pages, navigation and calls to action. Jesse James Garrett's five planes took us from strategy to structure to skeleton, and four principles tested every idea: Simplified, Personalised, Supported and Connected.","note":"Arrow draws. Vision halo and focus dot fade in, then four spokes draw out to Simplified, Personalised, Supported and Connected. Label: 03 Four principles."}]}
}
tpl = open('tpl.html').read()
os.makedirs('out', exist_ok=True)
for k,v in D.items():
    v = dict(v)
    v['imgs'] = ['data:image/png;base64,'+base64.b64encode(open(f'sb/{k}-{i+1}.png','rb').read()).decode() for i in range(v['layers'])]
    open(f'out/{k}.html','w').write(tpl.replace('__TITLE__',v['title']).replace('__DATA__',json.dumps(v)))
print(os.listdir('out'))
